// Texts for the «Почётная порция» auction page, kept apart from the main
// dictionaries.

const ru = {
  nav: "Аукцион",
  kicker: "Аукцион Крипто Ош",
  title: "Почётная порция",
  lead: "Первая порция плова дня с деликатесами. Её получает тот, кто предложит больше всех: сначала ставки на сайте, затем финал вживую на Оше.",
  metaTitle: "Аукцион «Почётная порция» на Крипто Ош",
  metaDescription:
    "Аукцион первой, почётной порции плова на Крипто Ош: ставки на сайте до встречи и финал вживую. Правила, даты и как принять участие.",
  preview: "Приём ставок ещё не открыт. Это превью страницы: ставки не принимаются, ничего никуда не переводите.",
  status: {
    title: "Следующий аукцион",
    date: "Дата Оша",
    place: "Город и площадка",
    start: "Стартовая ставка",
    step: "Минимальный шаг",
    closes: "Онлайн-ставки до",
    tba: "уточняется",
  },
  bidSoon: "Ставки откроются скоро",
  notify: "Узнать о старте в Telegram",
  whatTitle: "Что такое почётная порция",
  whatLead: "В узбекском застолье первую порцию плова принято подавать самому уважаемому гостю. На Крипто Оше это место за столом разыгрывается на аукционе.",
  what: [
    { title: "Первая порция дня", text: "Из первого казана, раньше, чем плов подадут остальным гостям." },
    { title: "Деликатесы", text: "К плову подаются деликатесы. Состав объявим перед Ошем." },
    { title: "Почёт при всех", text: "Ведущий называет победителя, и порцию подают ему первым на глазах у всех гостей." },
  ],
  howTitle: "Как проходит аукцион",
  how: [
    { step: "Ставки на сайте", text: "До встречи ставки принимаются здесь, на странице. Лидер и его ставка видны всем." },
    { step: "Финал на Оше", text: "Торги продолжаются вживую с лучшей онлайн-ставки. Гости повышают ставку прямо в зале." },
    { step: "Почётная порция", text: "Победитель оплачивает ставку и первым получает порцию из казана." },
  ],
  rulesTitle: "Правила",
  rules: [
    "Ставки указываются в USDT. Первая ставка не ниже стартовой, каждая следующая выше текущей на минимальный шаг или больше.",
    "Онлайн-ставку подтверждают организаторы, после этого она появляется в таблице. Участник выбирает, показывать имя или ник.",
    "Онлайн-этап закрывается накануне Оша. Лучшая онлайн-ставка становится стартовой в финале.",
    "В зале ставку повышают поднятой рукой или через QR-код на столе, ведущий фиксирует каждую сумму.",
    "Побеждает ставка, которую ведущий назвал три раза и никто не перебил. Если лидер онлайн-этапа не пришёл, его ставка всё равно участвует.",
    "Ставка — обязательство выкупить порцию. Если победитель не оплатил её до подачи плова, порция переходит предыдущей ставке.",
  ],
  bidsTitle: "Ставки",
  bidsCols: { name: "Участник", amount: "Ставка", at: "Когда" },
  bidsEmpty: "Ставок пока нет: приём откроется перед следующим Ошем.",
  payTitle: "Как будет проходить оплата",
  pay: [
    "Способ оплаты объявим до старта ставок. Мы примем оплату только законным путём: через провайдера криптоуслуг с лицензией НАПП или в сумах.",
    "Мы никогда не просим перевести криптовалюту на личный кошелёк в переписке. Реквизиты публикуются только на этой странице.",
  ],
  legal: "Криптоактивы не являются средством платежа в Узбекистане, за исключением случаев, установленных актами законодательства.",
  faqTitle: "Частые вопросы",
  faq: [
    { q: "Можно участвовать, если я не приду на Ош?", a: "Онлайн-ставка участвует в финале, даже если вас нет в зале. Но саму порцию подают на месте, поэтому её стоит забрать лично или передать гостю, которого вы назовёте заранее." },
    { q: "Можно отменить ставку?", a: "Нет. Ставка — обещание выкупить порцию, иначе аукцион теряет смысл для остальных участников." },
    { q: "Что будет, если ставок не будет?", a: "Тогда почётную порцию по традиции подадут самому уважаемому гостю Оша." },
  ],
  ctaTitle: "Хотите первым узнать о старте ставок?",
};

const uz: typeof ru = {
  nav: "Auksion",
  kicker: "Crypto Osh auksioni",
  title: "Faxriy porsiya",
  lead: "Kunning birinchi osh porsiyasi, noz-ne'matlar bilan. Uni eng yuqori narx taklif qilgan kishi oladi: avval saytda stavkalar, so'ng Osh davomida jonli final.",
  metaTitle: "Crypto Osh'da «Faxriy porsiya» auksioni",
  metaDescription:
    "Crypto Osh'da birinchi, faxriy osh porsiyasi auksioni: uchrashuvgacha saytda stavkalar va jonli final. Qoidalar, sanalar va qanday qatnashish mumkin.",
  preview: "Stavkalar qabul qilinishi hali ochilmagan. Bu sahifaning ko'rinishi: stavkalar qabul qilinmaydi, hech qayerga pul o'tkazmang.",
  status: {
    title: "Navbatdagi auksion",
    date: "Osh sanasi",
    place: "Shahar va joy",
    start: "Boshlang'ich stavka",
    step: "Minimal qadam",
    closes: "Onlayn stavkalar muddati",
    tba: "aniqlanmoqda",
  },
  bidSoon: "Stavkalar tez orada ochiladi",
  notify: "Boshlanishi haqida Telegramda bilish",
  whatTitle: "Faxriy porsiya nima",
  whatLead: "O'zbek dasturxonida birinchi osh porsiyasi eng hurmatli mehmonga tortiladi. Crypto Osh'da bu sharaf auksionda o'ynaladi.",
  what: [
    { title: "Kunning birinchi porsiyasi", text: "Birinchi qozondan, osh boshqa mehmonlarga tortilishidan oldin." },
    { title: "Noz-ne'matlar", text: "Osh noz-ne'matlar bilan tortiladi. Tarkibini Osh oldidan e'lon qilamiz." },
    { title: "Hamma oldida sharaf", text: "Boshlovchi g'olibning ismini aytadi va porsiya barcha mehmonlar ko'z oldida birinchi bo'lib unga tortiladi." },
  ],
  howTitle: "Auksion qanday o'tadi",
  how: [
    { step: "Saytda stavkalar", text: "Uchrashuvgacha stavkalar shu sahifada qabul qilinadi. Yetakchi va uning stavkasi hammaga ko'rinadi." },
    { step: "Osh'dagi final", text: "Savdo eng yaxshi onlayn stavkadan jonli davom etadi. Mehmonlar stavkani zalning o'zida oshiradi." },
    { step: "Faxriy porsiya", text: "G'olib stavkani to'laydi va qozondan birinchi porsiyani oladi." },
  ],
  rulesTitle: "Qoidalar",
  rules: [
    "Stavkalar USDT'da ko'rsatiladi. Birinchi stavka boshlang'ichdan past bo'lmasligi, har bir keyingisi joriy stavkadan kamida minimal qadamga yuqori bo'lishi kerak.",
    "Onlayn stavkani tashkilotchilar tasdiqlaydi, shundan so'ng u jadvalda paydo bo'ladi. Ishtirokchi ismi yoki taxallusini ko'rsatishni o'zi tanlaydi.",
    "Onlayn bosqich Osh arafasida yopiladi. Eng yaxshi onlayn stavka finalda boshlang'ich bo'ladi.",
    "Zalda stavka qo'l ko'tarib yoki stoldagi QR-kod orqali oshiriladi, boshlovchi har bir summani qayd etadi.",
    "Boshlovchi uch marta aytgan va hech kim oshirmagan stavka g'olib bo'ladi. Onlayn bosqich yetakchisi kelmasa ham, uning stavkasi ishtirok etadi.",
    "Stavka porsiyani sotib olish majburiyatidir. G'olib osh tortilgunicha to'lamasa, porsiya oldingi stavkaga o'tadi.",
  ],
  bidsTitle: "Stavkalar",
  bidsCols: { name: "Ishtirokchi", amount: "Stavka", at: "Qachon" },
  bidsEmpty: "Hozircha stavkalar yo'q: qabul navbatdagi Osh oldidan ochiladi.",
  payTitle: "To'lov qanday amalga oshiriladi",
  pay: [
    "To'lov usulini stavkalar boshlanishidan oldin e'lon qilamiz. To'lovni faqat qonuniy yo'l bilan qabul qilamiz: NAPP litsenziyasiga ega kripto-xizmat provayderi orqali yoki so'mda.",
    "Biz hech qachon yozishmada kriptovalyutani shaxsiy hamyonga o'tkazishni so'ramaymiz. Rekvizitlar faqat shu sahifada e'lon qilinadi.",
  ],
  legal: "Kripto-aktivlar O'zbekistonda to'lov vositasi hisoblanmaydi, qonunchilik hujjatlarida belgilangan hollar bundan mustasno.",
  faqTitle: "Ko'p beriladigan savollar",
  faq: [
    { q: "Osh'ga kela olmasam, qatnasha olamanmi?", a: "Onlayn stavka siz zalda bo'lmasangiz ham finalda ishtirok etadi. Ammo porsiyaning o'zi joyida tortiladi, shuning uchun uni shaxsan olgan yoki oldindan aytgan mehmoningizga topshirgan ma'qul." },
    { q: "Stavkani bekor qilsa bo'ladimi?", a: "Yo'q. Stavka porsiyani sotib olish va'dasi, aks holda auksion boshqa ishtirokchilar uchun ma'nosini yo'qotadi." },
    { q: "Stavkalar bo'lmasa nima bo'ladi?", a: "Unda faxriy porsiya an'anaga ko'ra Osh'ning eng hurmatli mehmoniga tortiladi." },
  ],
  ctaTitle: "Stavkalar boshlanishini birinchi bo'lib bilmoqchimisiz?",
};

const en: typeof ru = {
  nav: "Auction",
  kicker: "Crypto Osh auction",
  title: "The Honorary Portion",
  lead: "The first plate of plov of the day, served with delicacies. It goes to whoever offers the most: bids on the website first, then a live final at the Osh.",
  metaTitle: "The Honorary Portion auction at Crypto Osh",
  metaDescription:
    "Auction for the first, honorary plate of plov at Crypto Osh: online bids before the meetup and a live final. Rules, dates and how to take part.",
  preview: "Bidding is not open yet. This is a preview of the page: no bids are accepted, do not send any payment.",
  status: {
    title: "Next auction",
    date: "Osh date",
    place: "City and venue",
    start: "Starting bid",
    step: "Minimum raise",
    closes: "Online bids until",
    tba: "to be announced",
  },
  bidSoon: "Bidding opens soon",
  notify: "Get notified on Telegram",
  whatTitle: "What the Honorary Portion is",
  whatLead: "At an Uzbek table, the first plate of plov goes to the most respected guest. At Crypto Osh, that honour is auctioned.",
  what: [
    { title: "First plate of the day", text: "From the first kazan, before plov is served to the other guests." },
    { title: "Delicacies", text: "The plov comes with delicacies. We will announce what they are before the Osh." },
    { title: "Honoured in front of everyone", text: "The host names the winner, and the plate is served to them first in front of all the guests." },
  ],
  howTitle: "How the auction works",
  how: [
    { step: "Bids on the website", text: "Before the meetup, bids are taken here on this page. The leader and their bid are visible to everyone." },
    { step: "Final at the Osh", text: "Bidding continues live from the best online bid. Guests raise the bid right in the room." },
    { step: "The Honorary Portion", text: "The winner pays their bid and is served the first plate from the kazan." },
  ],
  rulesTitle: "Rules",
  rules: [
    "Bids are stated in USDT. The first bid is at least the starting bid; each next bid beats the current one by the minimum raise or more.",
    "The organisers confirm each online bid, and then it appears in the table. Bidders choose whether to show their name or a nickname.",
    "The online stage closes the day before the Osh. The best online bid becomes the starting bid of the final.",
    "In the room, bids are raised by hand or through the QR code on the table, and the host records every amount.",
    "The winning bid is the one the host calls three times without being beaten. If the online leader is not there, their bid still stands.",
    "A bid is a commitment to buy the portion. If the winner has not paid before the plov is served, the portion goes to the previous bid.",
  ],
  bidsTitle: "Bids",
  bidsCols: { name: "Bidder", amount: "Bid", at: "When" },
  bidsEmpty: "No bids yet: bidding opens before the next Osh.",
  payTitle: "How payment will work",
  pay: [
    "We will announce the payment method before bidding opens. We will only accept payment lawfully: through a crypto service provider licensed by NAPP, or in Uzbek sum.",
    "We never ask anyone to send crypto to a personal wallet in private messages. Payment details are published only on this page.",
  ],
  legal: "Crypto assets are not a means of payment in Uzbekistan, except in cases established by law.",
  faqTitle: "FAQ",
  faq: [
    { q: "Can I take part if I can't come to the Osh?", a: "Your online bid stays in the final even if you are not in the room. The portion itself is served on site, though, so collect it in person or name a guest in advance to receive it." },
    { q: "Can I cancel a bid?", a: "No. A bid is a promise to buy the portion; otherwise the auction loses its point for everyone else." },
    { q: "What if nobody bids?", a: "Then, by tradition, the Honorary Portion is served to the most respected guest at the Osh." },
  ],
  ctaTitle: "Want to hear first when bidding opens?",
};

export const auctionText = { ru, uz, en };
