import type { ru } from "./ru";

export const en: typeof ru = {
  meta: {
    title: "Crypto Osh — Uzbekistan's crypto community",
    description:
      "An open community and association of traders, web3 developers, KOLs and creators in Uzbekistan. Offline meetups over plov, networking and turnkey brand image events for business.",
  },
  nav: { home: "Home", about: "About", business: "For business", people: "Blockchain People", videos: "Videos", contact: "Contact", menu: "Menu" },
  hero: {
    eyebrow: "Uzbekistan's crypto association",
    tagline: "Crypto, blockchain and plov at one dasturkhan",
    subtitle:
      "Crypto Osh is an open community of crypto enthusiasts, traders, web3 builders and creators in Uzbekistan. We meet offline over plov to share knowledge, make real connections and grow blockchain in the country together.",
    ctaPrimary: "Host an event for your brand",
    ctaSecondary: "See how it went",
  },
  stats: [
    { value: "5+", label: "meetups in the series" },
    { value: "4", label: "regions of Uzbekistan" },
    { value: "120", label: "guests at the record Osh" },
    { value: "1", label: "kazan that brings us together" },
  ],
  about: {
    kicker: "Story",
    title: "How Crypto Osh began",
    paragraphs: [
      "In Uzbekistan, the conversations that matter happen over plov. We thought blockchain deserved the same: no stage and no pretence, just one shared table where traders sit with developers and creators sit with founders.",
      "Crypto Osh was founded by the open community and association of crypto enthusiasts of Uzbekistan, represented by Takhir Sultanov. Its purpose is to develop blockchain technology in Uzbekistan, bring together the people building it, and show that crypto can be literate, transparent and legal.",
      "It started with meetups in Tashkent. Then the format went on the road to Samarkand, Fergana and Khorezm. Every Osh brings new faces, fresh trends and a kazan of plov that brings everyone together.",
    ],
    more: "More about us",
  },
  timeline: {
    title: "Our path",
    items: [
      { label: "First gatherings", text: "Small crypto dinners over plov among like-minded people." },
      { label: "Vol.4 — BEK", text: "Market trends, plov and networking at BEK restaurant." },
      { label: "Vol.5 — Samarkand", text: "The first big trip: plov, crypto and future trends." },
      { label: "Fergana & Khorezm", text: "Osh in Fergana (2025) and a record meetup in Urgench with 120 guests." },
    ],
  },
  founder: {
    kicker: "Founder",
    title: "The open community and association of Uzbekistan's crypto enthusiasts",
    name: "Takhir Sultanov",
    role: "community representative, Web3 and blockchain enthusiast",
    text: "Crypto Osh belongs to its community. Takhir brings people to one table and makes sure every Osh is useful, honest and warm.",
  },
  mission: {
    kicker: "Mission",
    title: "Growing blockchain in Uzbekistan",
    intro: "We help Uzbekistan's blockchain industry grow in a way that is open, professional and within the law.",
    pillars: [
      { title: "Education", text: "Clear talks on markets, technology and security, for beginners and pros alike." },
      { title: "Networking", text: "Real introductions around one table. People find partners, teammates and investors in a single evening." },
      { title: "Developer ecosystem", text: "We back web3 builders by showcasing their projects and connecting them with business and the community." },
      { title: "Responsible crypto culture", text: "We promote using licensed providers in line with NAPP requirements and teach people to tell opportunity from risk." },
    ],
  },
  audience: {
    kicker: "Community",
    title: "Who joins",
    items: [
      { title: "Traders", text: "Market breakdowns, strategies and peer experience without the noise." },
      { title: "Web3 developers", text: "A place to show your product and find teammates and first users." },
      { title: "KOLs & creators", text: "Content, collaborations and access to the most active crypto crowd." },
      { title: "Entrepreneurs", text: "Market insight, partnerships and a new audience." },
    ],
  },
  gallery: { kicker: "Photo reports", title: "What an Osh looks like" },
  businessTeaser: {
    kicker: "For business",
    title: "A brand image event for your company",
    text: "Up to 50 guests, plov, a projector, a DJ, your presentation and your speaker. Then a YouTube video, 2 reels and 3 Telegram posts.",
    price: "29M UZS",
    cta: "See the offer",
  },
  business: {
    seoTitle: "Turnkey brand image event for business",
    seoDescription:
      "A brand image event in Uzbekistan: up to 50 guests, plov, a projector, a DJ, your speaker, a YouTube video, 2 reels and 3 Telegram posts. 29M UZS.",
    kicker: "For business · brand event",
    title: "A brand image event for your company",
    lead: "We gather up to 50 traders, web3 developers, creators and entrepreneurs around one dasturkhan. You present your company, your speaker takes the floor, and we film it and release content about your brand.",
    priceLabel: "Price",
    price: "29M UZS",
    priceNote: "up to 50 guests",
    heroAlt: "Plov at a Crypto Osh meetup",
    includesTitle: "What 29M UZS includes",
    includeGroups: [
      {
        title: "At the event",
        items: [
          { icon: "🍚", text: "Plov and hospitality for up to 50 guests: a true dasturkhan" },
          { icon: "👥", text: "Gathering the right audience: traders, developers, KOLs and business" },
          { icon: "📽️", text: "A projector and the chance to present your company" },
          { icon: "🎧", text: "A DJ and music" },
          { icon: "🎤", text: "A slot for one speaker, promoted by Crypto Osh" },
        ],
      },
      {
        title: "Content and promotion",
        items: [
          { icon: "📣", text: "Announcements in community channels and targeted ads" },
          { icon: "🎬", text: "Video footage from the event" },
          { icon: "▶️", text: "A YouTube video about the event" },
          { icon: "📱", text: "2 reels" },
          { icon: "✈️", text: "3 Telegram posts" },
        ],
      },
    ],
    moreGuests: "More than 50 guests? We agree on the format, venue and price individually.",
    imageTitle: "Why it builds your brand image",
    imageLead: "A brand image event with Crypto Osh builds a positive image for your company: people see a brand that backs technology and hosts its guests generously.",
    imagePoints: [
      { title: "Trust through hospitality", text: "Plov stands for generosity. A brand that hosts is remembered as one of us." },
      { title: "Face-to-face reach", text: "A real conversation with the people who make decisions in crypto and web3, not just another banner." },
      { title: "Content that lasts", text: "The YouTube video, reels and posts keep working for your brand long after dinner." },
      { title: "Aligned with progress", text: "Your brand becomes part of responsible, legal blockchain growth in Uzbekistan." },
    ],
    packagesTitle: "Packages",
    popular: "Popular",
    packages: [
      { name: "Start", price: "29M UZS", text: "Up to 50 guests. Plov, projector and presentation, DJ, a speaker slot, video, a YouTube video, 2 reels and 3 Telegram posts." },
      { name: "Partner", price: "on request", text: "More than 50 guests. Everything in Start, plus an extended format, venue branding and more content." },
      { name: "Title", price: "on request", text: "An exclusive event or a regional series with your brand fully built into the program." },
    ],
    processTitle: "How it works",
    process: [
      { step: "Request", text: "Tell us your goals, audience and number of guests." },
      { step: "Concept", text: "We propose the format, city, program and budget." },
      { step: "Preparation", text: "Announcements, ads, guests, venue, equipment and plov." },
      { step: "Osh & content", text: "We run the evening and release the YouTube video, reels and posts." },
    ],
    faqTitle: "FAQ",
    faq: [
      { q: "What does 29M UZS include?", a: "An event for up to 50 guests: plov and hospitality, audience gathering, announcements and targeted ads, a projector and the chance to present, a DJ, a slot for one speaker with promotion, video footage, a YouTube video, 2 reels and 3 Telegram posts." },
      { q: "What if we have more than 50 guests?", a: "Then we agree on the details individually: format, venue, program and price." },
      { q: "How is a brand image event different from advertising?", a: "An ad shows your brand; at an image event people get to know it. Guests talk with your team at one table and hear your presentation, and the video and posts keep working for the brand after the evening." },
      { q: "Can the event be outside Tashkent?", a: "Yes. We have already hosted Osh in Samarkand, Fergana and Khorezm." },
      { q: "How far ahead should we book?", a: "Ideally 3–4 weeks ahead, which leaves enough time for announcements and audience building." },
      { q: "Can crypto services be promoted?", a: "Yes, within Uzbek law. We work with projects that follow NAPP requirements and do not promote unlicensed platforms." },
    ],
    ctaTitle: "Let us set the dasturkhan for your brand",
    ctaButton: "Discuss an event",
  },
  people: {
    kicker: "Blockchain experts in Uzbekistan",
    title: "Blockchain People",
    intro: "Specialists, developers and entrepreneurs building blockchain and Web3 in Uzbekistan.",
    metaDescription: "Blockchain experts in Uzbekistan: specialists, developers and entrepreneurs building blockchain and Web3. Profiles of ecosystem members on the Crypto Osh website.",
    open: "View profile",
    back: "All Blockchain People",
    photoAlt: "Portrait of {name}",
    about: "About the specialist",
    directions: "Key areas",
    why: "Why this profile is in Blockchain People",
    links: "Links",
    disclaimer: "This profile is for information only and is not investment advice.",
  },
  videos: {
    kicker: "Videos",
    title: "Memory Library",
    intro: "Every Osh is a story: new faces, heated market debates and plov that brings everyone together. Here are the videos of our meetups across Uzbekistan.",
    play: "Play video",
    all: "Full library",
    privacy: "Videos load from YouTube only after you press play.",
  },
  contact: {
    title: "Get in touch",
    text: "Want to join the next Osh, speak at one, or host an event for your brand? Write to us.",
    group: "Join the Telegram group",
    telegram: "Message on Telegram",
    instagram: "Instagram",
    phone: "Call",
    soon: "Contacts will appear here very soon.",
  },
  footer: {
    tagline: "Crypto Osh: Uzbekistan's crypto enthusiast community",
    founder: "Founded by the open community and association of crypto enthusiasts of Uzbekistan, represented by Takhir Sultanov",
    disclaimer: "Content is for educational purposes only and is not investment advice.",
    rights: "All rights reserved.",
  },
  notFound: { title: "Page not found", back: "Back to home" },
};
