import type { ru } from "./ru";

export const uz: typeof ru = {
  meta: {
    title: "Kripto Osh — O'zbekiston kripto ishqibozlari hamjamiyati",
    description:
      "O'zbekistondagi treyderlar, web3 dasturchilar, KOL va blogerlarning ochiq hamjamiyati va assotsiatsiyasi. Osh atrofidagi oflayn uchrashuvlar, networking va biznes uchun tayyor tadbirlar.",
  },
  nav: { home: "Bosh sahifa", about: "Biz haqimizda", business: "Biznesga", videos: "Videolar", contact: "Bog'lanish", menu: "Menyu" },
  hero: {
    eyebrow: "O'zbekiston kriptanlari assotsiatsiyasi",
    tagline: "Kripto, blokcheyn va osh — bir dasturxon atrofida",
    subtitle:
      "Kripto Osh — O'zbekistondagi kripto ishqibozlari, treyderlar, web3 dasturchilar va blogerlarning ochiq hamjamiyati. Bilim almashish, tanishish va yurtimizda blokcheynni birga rivojlantirish uchun osh atrofida yig'ilamiz.",
    ctaPrimary: "Biznes uchun tadbir",
    ctaSecondary: "Qanday o'tganini ko'rish",
  },
  stats: [
    { value: "5+", label: "turkumdagi uchrashuvlar" },
    { value: "4", label: "O'zbekiston hududi" },
    { value: "120", label: "rekord Oshdagi mehmonlar" },
    { value: "1", label: "hammani birlashtiradigan qozon" },
  ],
  about: {
    kicker: "Tarix",
    title: "Kripto Osh qanday paydo bo'ldi",
    paragraphs: [
      "O'zbekistonda muhim suhbatlar osh ustida bo'ladi. Blokcheyn haqida ham shunday gaplashsa bo'ladi, deb o'yladik: sahnasiz, rasmiyatchiliksiz, umumiy dasturxon atrofida. U yerda treyder dasturchi bilan, bloger esa tadbirkor bilan yonma-yon o'tiradi.",
      "Kripto Osh'ni O'zbekiston kripto ishqibozlarining ochiq hamjamiyati va assotsiatsiyasi Tohir Sultonov timsolida tashkil etgan. Maqsad — yurtimizda blokcheyn texnologiyalarini rivojlantirish, ularni yaratayotgan odamlarni birlashtirish va kripto savodli, shaffof hamda qonuniy bo'lishi mumkinligini ko'rsatish.",
      "Avval Toshkentdagi uchrashuvlardan boshlandik. Keyin format viloyatlarga yo'l oldi: Samarqand, Farg'ona, Xorazm. Har bir Osh — yangi tanishlar, yangi trendlar va hammani birlashtiradigan bir qozon osh.",
    ],
    more: "Batafsil",
  },
  timeline: {
    title: "Hamjamiyat yo'li",
    items: [
      { label: "Ilk uchrashuvlar", text: "Hamfikrlar davrasida kichik kripto-osh kechalari." },
      { label: "Vol.4 — BEK", text: "BEK restoranida kripto trendlar, osh va networking." },
      { label: "Vol.5 — Samarqand", text: "Birinchi katta safar: osh, kripto va kelajak trendlari." },
      { label: "Farg'ona va Xorazm", text: "Farg'onada Osh (2025) va Urganchda rekord uchrashuv — 120 mehmon." },
    ],
  },
  founder: {
    kicker: "Asoschi",
    title: "O'zbekiston kriptanlarining ochiq hamjamiyati va assotsiatsiyasi",
    name: "Tohir Sultonov",
    role: "hamjamiyat vakili, Web3 va blokcheyn ishqibozi",
    text: "Kripto Osh hamjamiyatga tegishli. Tohir odamlarni bir dasturxon atrofida yig'adi va har bir Osh foydali, halol va samimiy bo'lishini kuzatadi.",
  },
  mission: {
    kicker: "Missiya",
    title: "O'zbekistonda blokcheynni rivojlantiramiz",
    intro: "O'zbekiston blokcheyn sohasining ochiq, professional va qonun doirasida o'sishiga yordam beramiz.",
    pillars: [
      { title: "Ta'lim", text: "Bozor, texnologiyalar va xavfsizlik haqida tushunarli ma'ruzalar — yangi boshlaganlar uchun ham, mutaxassislar uchun ham." },
      { title: "Networking", text: "Bir dasturxon atrofida jonli tanishuvlar. Hamkor, jamoa va investorni shu yerda topasiz." },
      { title: "Dasturchilar ekotizimi", text: "Web3 dasturchilarni qo'llab-quvvatlaymiz: loyihalarini ko'rsatamiz, biznes va hamjamiyat bilan bog'laymiz." },
      { title: "Mas'uliyatli kripto madaniyati", text: "NAPP talablariga muvofiq, litsenziyalangan provayderlar orqali ishlashni targ'ib qilamiz va imkoniyatni xavfdan ajratishni o'rgatamiz." },
    ],
  },
  audience: {
    kicker: "Hamjamiyat",
    title: "Biz bilan kimlar",
    items: [
      { title: "Treyderlar", text: "Bozor tahlili, strategiyalar va tajriba almashish — ortiqcha shovqinsiz." },
      { title: "Web3 dasturchilar", text: "Mahsulotni ko'rsatish, jamoa va ilk foydalanuvchilarni topish uchun maydon." },
      { title: "KOL va blogerlar", text: "Kontent, hamkorliklar va eng faol kripto hamjamiyat bilan aloqa." },
      { title: "Tadbirkorlar", text: "Bozorni tushunish, hamkorlik va yangi auditoriya." },
    ],
  },
  gallery: { kicker: "Fotohisobotlar", title: "Osh qanday o'tadi" },
  businessTeaser: {
    kicker: "Biznesga",
    title: "Brendingiz uchun tayyor tadbir",
    text: "Osh, e'lonlar, mehmonlarni yig'ish, target, foto va video, taklif etilgan spikerlar. Hammasini o'zimiz qilamiz.",
    price: "29 mln so'mdan",
    cta: "Taklifni ko'rish",
  },
  business: {
    kicker: "Biznesga",
    title: "Biznes uchun Kripto Osh",
    lead: "Brendingiz uchun tayyor tadbir — 29 mln so'mdan. Osh, mehmonlar, spikerlar va kontent bizning zimmamizda.",
    priceLabel: "Narxi",
    price: "29 mln so'mdan",
    includesTitle: "Nimalar kiradi",
    includes: [
      "Osh va mehmondo'stlik — mehmonlar uchun haqiqiy dasturxon",
      "Hamjamiyat kanallarida tadbir e'lonlari",
      "Maqsadli auditoriyani yig'ish: treyderlar, dasturchilar, KOL, biznes",
      "Targetlangan reklama",
      "Foto va video prodakshn, ijtimoiy tarmoqlar uchun tayyor roliklar",
      "Taklif etilgan spikerlar",
    ],
    imageTitle: "Bu brend imijiga qanday ta'sir qiladi",
    imageLead: "Kripto Osh bilan tadbir kompaniyangizning ijobiy imijini shakllantiradi: sizni texnologiyalarni qo'llab-quvvatlaydigan va mehmonni saxovat bilan kutib oladigan brend sifatida ko'rishadi.",
    imagePoints: [
      { title: "Mehmondo'stlik orqali ishonch", text: "Osh — saxovat ramzi. Mehmon qilgan brend o'zimizniki bo'lib eslab qolinadi." },
      { title: "Auditoriya bilan jonli aloqa", text: "Banner emas, kripto va web3'da qaror qabul qiladigan odamlar bilan yuzma-yuz suhbat." },
      { title: "Uzoq yashaydigan kontent", text: "Video va fotolar tadbirdan keyin ham brendingiz uchun ishlayveradi." },
      { title: "Taraqqiyot bilan assotsiatsiya", text: "Brendingiz O'zbekistonda mas'uliyatli va qonuniy blokcheyn rivojining bir qismiga aylanadi." },
    ],
    packagesTitle: "Paketlar",
    popular: "Ommabop",
    packages: [
      { name: "Start", price: "29 mln so'mdan", text: "Osh, e'lonlar, mehmonlarni yig'ish, target, foto-video, spikerlar." },
      { name: "Hamkor", price: "so'rov bo'yicha", text: "«Start»dagi hammasi, ustiga kengaytirilgan format, maydon brendingi va ko'proq kontent." },
      { name: "Bosh hamkor", price: "so'rov bo'yicha", text: "Eksklyuziv tadbir yoki viloyatlarda turkum, brendning dasturga to'liq integratsiyasi." },
    ],
    processTitle: "Qanday ishlaymiz",
    process: [
      { step: "Ariza", text: "Maqsad va auditoriyangiz haqida aytib berasiz." },
      { step: "Konsepsiya", text: "Format, shahar, spikerlar va smetani taklif qilamiz." },
      { step: "Tayyorgarlik", text: "E'lonlar, target, mehmonlar, maydon va osh." },
      { step: "Osh va hisobot", text: "Tadbirni o'tkazamiz, foto, video va natijalarni topshiramiz." },
    ],
    faqTitle: "Ko'p so'raladigan savollar",
    faq: [
      { q: "29 mln so'mlik narxga nimalar kiradi?", a: "Osh, e'lonlar, mehmonlarni yig'ish, targetlangan reklama, foto-video prodakshn va taklif etilgan spikerlar. Aniq smeta format va mehmonlar soniga bog'liq." },
      { q: "Tadbirni Toshkentdan tashqarida o'tkazsa bo'ladimi?", a: "Ha. Oshlarimiz Samarqand, Farg'ona va Xorazmda ham bo'lib o'tgan." },
      { q: "Qancha oldin murojaat qilish kerak?", a: "Eng yaxshisi 3–4 hafta oldin. Shunda e'lon va auditoriya yig'ish uchun vaqt yetadi." },
      { q: "Kripto xizmatlarni reklama qilsa bo'ladimi?", a: "Ha, O'zbekiston qonunchiligi doirasida. NAPP talablariga rioya qiladigan loyihalar bilan ishlaymiz, litsenziyasiz platformalarni targ'ib qilmaymiz." },
    ],
    ctaTitle: "Brendingiz uchun dasturxon yozamiz",
    ctaButton: "Tadbirni muhokama qilish",
  },
  videos: {
    kicker: "Videolar",
    title: "Xotiralar kutubxonasi",
    intro: "Har bir Osh — bu bir hikoya: yangi chehralar, bozor haqida qizg'in bahslar va hammani birlashtiradigan osh. Bu yerda O'zbekistonning turli shaharlaridagi uchrashuvlarimiz videolari jamlangan.",
    play: "Videoni ko'rish",
    all: "Butun kutubxona",
    privacy: "Video YouTube'dan faqat bosilgandan keyin yuklanadi.",
  },
  contact: {
    title: "Biz bilan bog'lanish",
    text: "Keyingi Oshga kelmoqchimisiz, spiker bo'lmoqchimisiz yoki brendingiz uchun tadbir o'tkazmoqchimisiz? Bizga yozing.",
    telegram: "Telegram'da yozish",
    instagram: "Instagram",
    phone: "Qo'ng'iroq qilish",
    soon: "Kontaktlar tez orada shu yerda paydo bo'ladi.",
  },
  footer: {
    tagline: "Kripto Osh — O'zbekiston kripto ishqibozlari hamjamiyati",
    founder: "Asoschi: O'zbekiston kripto ishqibozlarining ochiq hamjamiyati va assotsiatsiyasi, Tohir Sultonov timsolida",
    disclaimer: "Materiallar ta'limiy xarakterga ega va investitsiya tavsiyasi emas.",
    rights: "Barcha huquqlar himoyalangan.",
  },
  notFound: { title: "Sahifa topilmadi", back: "Bosh sahifaga" },
};
